### ISSUE TITLE
Log level judgement issue

### ISSUE THREAD

**Issue by fan123199** [munix/LogcatTextView#1]
Line 120 in LogcatTextView.java 
```java
if ( line.contains( " I " ) ) {
    lineColor = infoColor;
} else if ( line.contains( " E " ) ) {
    lineColor = errorColor;
} else if ( line.contains( " D " ) ) {
    lineColor = debugColor;
} else if ( line.contains( " W " ) ) {
    lineColor = warningColor;
}
```
> sorry, I thought you are a Chinese by mistake.

I think if you use 'line.contains( " I " ) ', it goes wrong when the log message also contains the charactor. So I think it should use regex pattern to judge the log level. But I am not sure what I say is correct, so open an issue to you.

**Comment by munix** [comment]
Please send a pull request with best solution. And write me in english or spanish please :smile:
